version: '3.4'
services:
  lease:
    build: .
    image: kaiml/lease:latest
    ports:
    - "8888:8888"
    volumes:
    -  .:/app
    command: pipenv run jupyter notebook --ip 0.0.0.0 --no-browser --allow-root
