name: Demo
on:
  pull_request:
    type: opened # PRs == Issues in GitHub

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      # This step listens to all PR events for the triggering phrase
      - name: listen for PR Comments
        id: prcomm
        uses: machine-learning-apps/actions-impersonate@master
        with:
          APP_PEM: ${{ secrets.APP_PEM }}
          APP_ID: ${{ secrets.APP_ID }}

      # Get App Installation Token From Previous Step
      - name: Get App Instllation Token
        if: steps.prcomm.outputs.TRIGGERED == 'true'
        run: |
          echo "This token is masked: ${TOKEN}"
        env:
          TOKEN: ${{ steps.prcomm.outputs.APP_INSTALLATION_TOKEN }}
