name: ML Workflow Via Actions
on:
  pull_request:
    types: [labeled]

jobs:
  ml-workflow:
    if: github.actor == 'kaiml-chatops[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Copy Repository Contents
        uses: actions/checkout@master

      - name: Trigger on PR Label
        id: label
        run: python gha/validate_payload.py
        env:
          TRIGGER_LABEL_NAME: "Full Test Pending"

      - name: Publish CPU Image to DockerHub
        if: steps.label.outputs.TRIGGERED == 'true'
        run: |
          cd $GITHUB_WORKSPACE
          echo ${PASSWORD} | docker login -u $USERNAME --password-stdin
          BASE_NAME="kaiml/lease"
          IMAGE_NAME="$BASE_NAME:$GITHUB_SHA"
          docker pull $BASE_NAME || true
          docker build --cache-from $BASE_NAME -t $IMAGE_NAME -t $BASE_NAME -f Dockerfile .
          docker push $IMAGE_NAME
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Argo Param File
        if: steps.label.outputs.TRIGGERED == 'true'
        run: |
          cd $GITHUB_WORKSPACE
          echo "GITHUB-SHA: $SHA" >> argo/params.yaml
          echo "PR-NUMBER: $PR_NUMBER" >> argo/params.yaml
          echo "REPO: $GITHUB_REPOSITORY" >> argo/params.yaml
        env:
          SHA: ${{ steps.label.outputs.HEAD_SHA }}
          PR_NUMBER: ${{ steps.label.outputs.ISSUE_NUMBER }}

      - name: Submit Argo Deployment
        if: steps.label.outputs.TRIGGERED == 'true'
        id: argo
        uses: machine-learning-apps/gke-argo@master
        with:
          ARGO_URL: ${{ secrets.ARGO_URI }}
          APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          PROJECT_ID: "kaiml-argo"
          LOCATION_ZONE: "asia-northeast1-a"
          CLUSTER_NAME: "kaiml-argo"
          WORKFLOW_YAML_PATH: "argo/workflow.yml"
          PARAMETER_FILE_PATH: "argo/params.yml"
          SHA: ${{ steps.label.outputs.HEAD_SHA }}

      - name: Create Check
        if: steps.label.outputs.TRIGGERED == 'true'
        run: |
          python3 gha/create_check_run.py "in_progress" "Argo-Workflow" "ML Workflow For SHA $SHA" "Links [Argo Workflow]($ARGO_LINK) | [W&B Project](https://app.wandb.ai/$WANDB_ENTITY/$WANDB_PROJECT) | Docker: [hamelsmu/ml-cicd](https://cloud.docker.com/u/hamelsmu/repository/docker/hamelsmu/ml-cicd), [hamelsmu/ml-cicd-gpu](https://cloud.docker.com/u/hamelsmu/repository/docker/hamelsmu/ml-cicd-gpu)" " "
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ARGO_LINK: ${{ steps.argo.outputs.WORKFLOW_URL }}
          WANDB_ENTITY: "kaiml"
          WANDB_PROJECT: "lease"
          SHA: ${{ steps.label.outputs.HEAD_SHA }}

      - name: Comment With Metadata
        if: steps.label.outputs.TRIGGERED == 'true'
        run: |
          bash gha/pr_comment.sh "### [ML Workflow]($ARGO_LINK) For SHA $SHA has been instantiated.\n\nThe following Docker images were built and tagged with the SHA: \n - [hamelsmu/ml-cicd](https://cloud.docker.com/u/hamelsmu/repository/docker/hamelsmu/ml-cicd)\n - [hamelsmu/ml-cicd-gpu](https://cloud.docker.com/u/hamelsmu/repository/docker/hamelsmu/ml-cicd-gpu)\n\nCheck run \`Argo-Workflow\` created, with status pending completion of the workflow."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ARGO_LINK: ${{ steps.argo.outputs.WORKFLOW_URL }}
          WANDB_ENTITY: "kaiml"
          WANDB_PROJECT: "lease"
          ISSUE_NUMBER: ${{ steps.label.outputs.ISSUE_NUMBER }}
          SHA: ${{ steps.label.outputs.HEAD_SHA }}
